export interface ProductProductOut {
  message_attachment_count: number;
  sale_ok: boolean;
  message_unread_counter: number;
  image_variant: string;
  outgoing_qty: number;
  image: string;
  list_price: number;
  message_needaction: boolean;
  product_variant_count: number;
  lst_price: number;
  attribute_line_ids: number[];
  property_stock_inventory: Array<number | string>;
  purchase_ok: boolean;
  type: string;
  message_is_follower: boolean;
  packaging_ids: any[];
  valid_archived_variant_ids: any[];
  uom_id: Array<number | string>;
  display_name: string;
  description_picking: boolean;
  activity_state: boolean;
  active: boolean;
  valid_existing_variant_ids: number[];
  message_partner_ids: number[];
  attribute_value_ids: number[];
  activity_summary: boolean;
  description: boolean;
  categ_id: Array<number | string>;
  image_small: string;
  message_has_error_counter: number;
  code: string;
  price: number;
  is_product_variant: boolean;
  partner_ref: string;
  uom_po_id: Array<number | string>;
  valid_product_template_attribute_line_ids: number[];
  reordering_max_qty: number;
  reordering_min_qty: number;
  weight_uom_id: Array<number | string>;
  description_sale: string;
  description_pickingout: boolean;
  uom_name: string;
  pricelist_id: boolean;
  write_date: Date;
  standard_price: number;
  color: number;
  product_variant_id: Array<number | string>;
  warehouse_id: boolean;
  orderpoint_ids: any[];
  message_follower_ids: number[];
  product_variant_ids: number[];
  activity_type_id: boolean;
  barcode: boolean;
  virtual_available: number;
  valid_product_attribute_wnva_ids: number[];
  valid_product_template_attribute_line_wnva_ids: number[];
  company_id: Array<number | string>;
  weight: number;
  message_unread: boolean;
  name: string;
  create_date: Date;
  default_code: string;
  write_uid: Array<number | string>;
  product_tmpl_id: Array<number | string>;
  qty_available: number;
  activity_date_deadline: boolean;
  description_pickingin: boolean;
  volume: number;
  sale_delay: number;
  route_ids: any[];
  item_ids: any[];
  location_id: boolean;
  pricelist_item_ids: any[];
  stock_quant_ids: any[];
  message_channel_ids: any[];
  rental: boolean;
  seller_ids: any[];
  currency_id: Array<number | string>;
  route_from_categ_ids: any[];
  description_purchase: boolean;
  create_uid: Array<number | string>;
  message_main_attachment_id: boolean;
  property_stock_production: Array<number | string>;
  id: number;
  weight_uom_name: string;
  incoming_qty: number;
  activity_user_id: boolean;
  responsible_id: Array<number | string>;
  valid_product_attribute_value_wnva_ids: number[];
  message_needaction_counter: number;
  price_extra: number;
  cost_currency_id: Array<number | string>;
  valid_product_attribute_value_ids: number[];
  product_template_attribute_value_ids: number[];
  stock_move_ids: any[];
  message_has_error: boolean;
  image_medium: string;
  tracking: string;
  variant_seller_ids: any[];
  valid_product_attribute_ids: number[];
  activity_ids: any[];
  sequence: number;
  __last_update: Date;
  message_ids: number[];
  nbr_reordering_rules: number;
}
